# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField(verbose_name=b'Expiry Date')),
                ('batch_no', models.CharField(max_length=100)),
                ('medicine_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(10)])),
            ],
        ),
    ]
