# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
