# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170311_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
