# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 04:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
